
TENSORFLOW USERS:
You must use the python3.6-anaconda/5.2.0 module to run TensorFlow.
See https://arc-ts.umich.edu/greatlakes/software/tensorflow for more
information.



The following have been reloaded with a version change:
  1) cuda/10.0.130 => cuda/10.1.105


Currently Loaded Modules:
  1) python3.7-anaconda/2019.07   2) cudnn/10.0-v7.6   3) cuda/10.1.105

 

mkdir: cannot create directory ‘results/5321083’: File exists
Traceback (most recent call last):
  File "tff_main.py", line 26, in <module>
    p1.go(test)
  File "/home/apawlik/federated/1_each_client_partially_iid.py", line 158, in go
    self.train()
  File "/home/apawlik/federated/partitioner.py", line 188, in train
    state, metrics = self.iterative_process.next(state, federated_train_data)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/utils/function_utils.py", line 680, in __call__
    return context.invoke(self, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/apawlik/.local/lib/python3.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/home/apawlik/.local/lib/python3.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/apawlik/.local/lib/python3.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/execution_context.py", line 175, in invoke
    _invoke(executor, comp, arg))
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/execution_context.py", line 118, in _invoke
    result = await executor.create_call(comp, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 296, in create_call
    return await self.create_call(eval_result, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 284, in create_call
    return await comp_repr(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 377, in _comp_fn
    LambdaExecutorScope({name: arg}, scope))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 426, in _evaluate
    value = await self._evaluate(loc.value, scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 430, in _evaluate
    return await self._evaluate(comp.block.result, scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 399, in _evaluate
    LambdaExecutorValue(comp.selection.source, scope=scope)),
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 299, in create_call
    return await self.create_call(eval_result, arg=None)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 399, in _evaluate
    LambdaExecutorValue(comp.selection.source, scope=scope)),
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 299, in create_call
    return await self.create_call(eval_result, arg=None)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 275, in create_call
    return await self.create_call(comp, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 296, in create_call
    return await self.create_call(eval_result, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 282, in create_call
    comp_repr, delegated_arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/caching_executor.py", line 271, in create_call
    target_value = await cached_value.target_future
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 275, in create_call
    return await self.create_call(comp, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 296, in create_call
    return await self.create_call(eval_result, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 282, in create_call
    comp_repr, delegated_arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/caching_executor.py", line 271, in create_call
    target_value = await cached_value.target_future
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 275, in create_call
    return await self.create_call(comp, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 296, in create_call
    return await self.create_call(eval_result, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 282, in create_call
    comp_repr, delegated_arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/caching_executor.py", line 271, in create_call
    target_value = await cached_value.target_future
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 275, in create_call
    return await self.create_call(comp, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 296, in create_call
    return await self.create_call(eval_result, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 282, in create_call
    comp_repr, delegated_arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/caching_executor.py", line 271, in create_call
    target_value = await cached_value.target_future
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/concurrent_executor.py", line 71, in create_call
    return await self._delegate(self._target_executor.create_call(comp, arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/federated_executor.py", line 345, in create_call
    return await coro(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/federated_executor.py", line 490, in _compute_intrinsic_federated_map
    return await self._map(arg, all_equal=False)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/federated_executor.py", line 438, in _map
    c.create_call(f, v) for c, (f, v) in zip(children, list(zip(fns, val)))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 296, in create_call
    return await self.create_call(eval_result, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 282, in create_call
    comp_repr, delegated_arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/caching_executor.py", line 271, in create_call
    target_value = await cached_value.target_future
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/concurrent_executor.py", line 71, in create_call
    return await self._delegate(self._target_executor.create_call(comp, arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/eager_executor.py", line 409, in create_call
    comp.internal_representation(arg.internal_representation),  # pytype: disable=attribute-error
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/eager_executor.py", line 178, in <lambda>
    return lambda arg: fn_to_return(arg)  # pylint: disable=unnecessary-lambda
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/eager_executor.py", line 165, in <lambda>
    fn_to_return = lambda arg, p=param_fns, w=wrapped_fn: _fn_to_return(arg, p, w)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/eager_executor.py", line 144, in _fn_to_return
    result_parts = wrapped_fn(*param_elements)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1091, in _call_impl
    return self._call_flat(args, self.captured_inputs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:   [_Derived_]  Received a label value of -9223372036854775808 which is outside the valid range of [0, 10).  Label values: 0 0 0 0 -9223372036854775808 0 0 7429827040011620 0 0 0 0 0 0 0 0 0 0 0 0
	 [[{{node StatefulPartitionedCall/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]
	 [[StatefulPartitionedCall]]
	 [[import/StatefulPartitionedCall_1/ReduceDataset]] [Op:__inference_wrapped_function_17946]

Function call stack:
wrapped_function -> wrapped_function -> wrapped_function -> wrapped_function

ERROR:concurrent.futures:exception calling callback for <Future at 0x2b10013bf0f0 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b0fb3e4c8d0 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b104646d630 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b1045db12e8 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b0fb3e52dd8 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b100348f2e8 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b104646d828 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b1045b144e0 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b100348f588 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b0f97fec4a8 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b10034bed30 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b104646db70 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b104644d828 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b1045a4ed30 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b104646dc50 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b1045d427b8 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b104646d908 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b0f97fec240 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b1001e29c88 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Traceback (most recent call last):
  File "tff_main.py", line 26, in <module>
    p1.go(test)
  File "/home/apawlik/federated/1_each_client_partially_iid.py", line 158, in go
    self.train()
  File "/home/apawlik/federated/partitioner.py", line 188, in train
    state, metrics = self.iterative_process.next(state, federated_train_data)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/utils/function_utils.py", line 680, in __call__
    return context.invoke(self, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/apawlik/.local/lib/python3.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/home/apawlik/.local/lib/python3.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/apawlik/.local/lib/python3.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/execution_context.py", line 175, in invoke
    _invoke(executor, comp, arg))
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/execution_context.py", line 118, in _invoke
    result = await executor.create_call(comp, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 296, in create_call
    return await self.create_call(eval_result, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 284, in create_call
    return await comp_repr(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 377, in _comp_fn
    LambdaExecutorScope({name: arg}, scope))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 426, in _evaluate
    value = await self._evaluate(loc.value, scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 430, in _evaluate
    return await self._evaluate(comp.block.result, scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 399, in _evaluate
    LambdaExecutorValue(comp.selection.source, scope=scope)),
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 299, in create_call
    return await self.create_call(eval_result, arg=None)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 399, in _evaluate
    LambdaExecutorValue(comp.selection.source, scope=scope)),
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 299, in create_call
    return await self.create_call(eval_result, arg=None)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 274, in create_call
    arg = await self.create_call(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 416, in _evaluate
    values = await asyncio.gather(*values)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 275, in create_call
    return await self.create_call(comp, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 296, in create_call
    return await self.create_call(eval_result, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 282, in create_call
    comp_repr, delegated_arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/caching_executor.py", line 271, in create_call
    target_value = await cached_value.target_future
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 275, in create_call
    return await self.create_call(comp, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 296, in create_call
    return await self.create_call(eval_result, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 282, in create_call
    comp_repr, delegated_arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/caching_executor.py", line 271, in create_call
    target_value = await cached_value.target_future
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 275, in create_call
    return await self.create_call(comp, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 296, in create_call
    return await self.create_call(eval_result, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 282, in create_call
    comp_repr, delegated_arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/caching_executor.py", line 271, in create_call
    target_value = await cached_value.target_future
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 289, in create_call
    eval_result = await self._evaluate(comp_repr, comp.scope)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 394, in _evaluate
    LambdaExecutorValue(comp.call.function, scope=scope), arg=arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 275, in create_call
    return await self.create_call(comp, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 296, in create_call
    return await self.create_call(eval_result, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 282, in create_call
    comp_repr, delegated_arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/caching_executor.py", line 271, in create_call
    target_value = await cached_value.target_future
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/concurrent_executor.py", line 71, in create_call
    return await self._delegate(self._target_executor.create_call(comp, arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/federated_executor.py", line 345, in create_call
    return await coro(arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/federated_executor.py", line 490, in _compute_intrinsic_federated_map
    return await self._map(arg, all_equal=False)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/federated_executor.py", line 438, in _map
    c.create_call(f, v) for c, (f, v) in zip(children, list(zip(fns, val)))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 296, in create_call
    return await self.create_call(eval_result, arg)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/lambda_executor.py", line 282, in create_call
    comp_repr, delegated_arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/caching_executor.py", line 271, in create_call
    target_value = await cached_value.target_future
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/concurrent_executor.py", line 71, in create_call
    return await self._delegate(self._target_executor.create_call(comp, arg))
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/executor_utils.py", line 266, in fn_to_return
    to_return = await func(*args, **kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/eager_executor.py", line 409, in create_call
    comp.internal_representation(arg.internal_representation),  # pytype: disable=attribute-error
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/eager_executor.py", line 178, in <lambda>
    return lambda arg: fn_to_return(arg)  # pylint: disable=unnecessary-lambda
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/eager_executor.py", line 165, in <lambda>
    fn_to_return = lambda arg, p=param_fns, w=wrapped_fn: _fn_to_return(arg, p, w)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_federated/python/core/impl/eager_executor.py", line 144, in _fn_to_return
    result_parts = wrapped_fn(*param_elements)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1091, in _call_impl
    return self._call_flat(args, self.captured_inputs)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/apawlik/.local/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:   [_Derived_]  Received a label value of -9223372036854775808 which is outside the valid range of [0, 10).  Label values: 0 0 0 0 -9223372036854775808 0 0 7429827040011620 0 0 0 0 0 0 0 0 0 0 0 0
	 [[{{node StatefulPartitionedCall/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]
	 [[StatefulPartitionedCall]]
	 [[import/StatefulPartitionedCall_1/ReduceDataset]] [Op:__inference_wrapped_function_17444]

Function call stack:
wrapped_function -> wrapped_function -> wrapped_function -> wrapped_function

ERROR:concurrent.futures:exception calling callback for <Future at 0x2b98a7ec88d0 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b98eeca1710 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b992908d588 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b9849f606a0 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b9929463d30 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b98a7f14940 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b98eff590f0 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b98a7ec8128 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b9928f30208 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b98a7e90b70 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b98a7f1a390 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b98ed008898 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b9928e68ba8 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b987ff9d048 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b987ffb0e80 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b987fb2d630 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b9849e884e0 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b984dc78a90 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:concurrent.futures:exception calling callback for <Future at 0x2b9849e7ae80 state=finished returned EagerValue>
Traceback (most recent call last):
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/sw/arcts/centos7/python3.7-anaconda/2019.07/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
mv: cannot stat ‘results/s.8.log’: No such file or directory
